version: "3.7"

services:
  libvirt-exporter:
    container_name: libvirt-exporter
    image: ycy1766/libvirt_exporter:v0.1.1
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
    ports:
      - "9177:9177"
    network_mode: "host"
